language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: pfinal-isi-rodrigo
  api_key:
    secure: tid792mdxT+5lJyIudc4bw6LcFq6pHyfms15qdJDUbCBMZVZQuUz+Ze0aQLBpJoahrR0W1jQ33gZveUZ3xkfZ7etTuNNkpX0ZA8hJClnsLJ8C8xH4kqErbJroITDvPVx9Mmg7uMIgZAoAshMqOgsmNXN/lLizZD4Pj4B+/YWoqBXtQN//W9KqatTYFdKRq9JjIzD+JAr4mdeQlwXfzOzCmvjw5plSYZpGFiWuhvlTFVaIcAM6k7Yqhopanarj2lQtlZZZkgj+p0oTGP0iZNt/3s+GoQxBS8cMBcXKSbybzjj3YIXitZ3RhbQE/fQ1AU1kIVZbgh0xY0pe9J0zo2aaBIP/I/08aF7dog0LzcJxwAzevN2pNKQqlquG7/9ckKiELRfYTVIgsPw2gJJx4ohdInLqxVuy2lDA0kCy4euEYnNMs5j+3t4yr50ZiGWDE0LYmPBRQg3w25dY41KN4UaLDjClJ0daQ6nnhpKosYMStr/WbDQgP05qfZU2ztDSy2IkwgXHplNBcY2QqJXiKvqXfOyNnyUnVrsRQYbQtz6rPz/V+BV/cSFZMQfMcDDG+VEQS5UPZLOZJfwmvkXdDKFzU/ZAUfzg3nMRrHOm9wOafpk+t3kOV1gxy7Z0Voq8PCRDkQmc4ZqV7TNU5EOBerSoGKU5sI5qxs7nhC7ioea5cM=
